language: cpp
cache: ccache

# We require CMake 3.10 but on Travis ARM xenial is too old (3.5)
dist: bionic
group: edge
virt: lxd

os:
  - linux
osx_image: xcode11.3

arch:
  - amd64
  - arm64
  - arm64-graviton2
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - ninja-build
  homebrew:
    packages:
      - ninja
      - ccache
    update:
      true

#matrix:
#  include:
#    - os: osx
#      compiler: clang
#   - os: osx
#      compiler: gcc
#      env:
#        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"
script:
  - hack/hack
